version: '2'
services:
  db:
    image: postgres
#    volumes:
#            - /opt/starter/psql:/var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"

  cache1:
    image: memcached
    ports:
      - "11211:11211"

  cache2:
    image: memcached
    ports:
      - "11212:11212"

  static_nginx:
    build: ./static_nginx
    ports:
      - "80:80"

  django_app_1:
     build: ./fietsenrek
     links:
        - db:db
        - cache1:cache1
        - cache2:cache2
     expose:
      - "8000"
     depends_on:
       - db

  django_app_2:
    build: ./fietsenrek
    links:
      - db:db
      - cache1:cache1
      - cache2:cache2
    expose:
      - "8000"
    depends_on:
     - db

  load_balancer:
    build: ./load_balancer
    ports:
      - "9999:9999"
    depends_on:
      - django_app_1
      - django_app_2
    links:
      - django_app_1:django_app_1
      - django_app_2:django_app_2
